### ISSUE TITLE
PA Review: Wiki Pages

### ISSUE THREAD

**Issue by aycelacap** [Shhmabbey/bold#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

**Comment by aycelacap** [comment]
Hey Zach. Go ahead and make bullet points and follow the formatting we have on Bluebird's repo for wiki pages. You'll need to create a link to the live page (you can use the real site for now), and ensure everything is correctly formatted. https://github.com/appacademy/bluebird/wiki

**Comment by Shhmabbey** [comment]
Thanks Ayce! I added a link to the repository as a placeholder. Does that look okay?
